import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/docs/": [
    {
      text: "快速开始",
      icon: "rocket",
      prefix: "register/",
      collapsible: false,
      children: [
        "1-register.md",
        "2-login.md",
        "3-quota.md",
        "4-token.md",
        "5-env.md",
        "6-cli.md",
      ],
    },
    {
      text: "用户中心",
      icon: "user",
      prefix: "user/",
      collapsible: true,
      children: [
        "dashboard.md",
        "api-key.md",
        "usage-billing.md",
        "redeem-affiliate-orders.md",
        "channels.md",
        "troubleshooting.md",
      ],
    },
    {
      text: "模型分组介绍",
      icon: "layer-group",
      prefix: "token/",
      collapsible: true,
      children: ["1-intro.md", "2-group.md"],
    },
    {
      text: "API 接入",
      icon: "code",
      prefix: "api/",
      collapsible: true,
      children: [
        "openai-compatible.md",
        "anthropic-compatible.md",
        "gemini-compatible.md",
        "images.md",
        "errors.md",
      ],
    },
    {
      text: "CC-Switch 使用",
      icon: "shuffle",
      prefix: "ccswitch/",
      collapsible: true,
      children: [
        "1-common.md",
        "2-claude.md",
        "3-codex.md",
        "4-gemini.md",
        "5-ccs_cli.md",
      ],
    },
    {
      text: "CLI 配置教程",
      icon: "terminal",
      prefix: "cli/",
      collapsible: true,
      children: [
        "1-env.md",
        "2-claude.md",
        "3-codex.md",
        "4-gemini.md",
        "5-cache-fix.md",
      ],
    },
    {
      text: "绘图模型教程",
      icon: "palette",
      prefix: "paint/",
      collapsible: true,
      children: ["Banana.md", "GPTImage.md"],
    },
    {
      text: "第三方接入",
      icon: "puzzle-piece",
      prefix: "advanced/",
      collapsible: true,
      children: [
        "ClaudeDesktop.md",
        "AionUI.md",
        "OpenCode.md",
        "OpenClaw.md",
      ],
    },
    {
      text: "部署运维",
      icon: "server",
      prefix: "deploy/",
      collapsible: true,
      children: ["overview.md", "local-incremental.md", "operations.md"],
    },
    {
      text: "管理后台",
      icon: "user-shield",
      prefix: "admin/",
      collapsible: true,
      children: [
        "overview.md",
        "accounts-groups.md",
        "payment.md",
        "compliance.md",
        "ops-troubleshooting.md",
      ],
    },
    {
      text: "常见问题",
      icon: "circle-question",
      prefix: "faq/",
      collapsible: true,
      children: ["CC.md", "Codex.md", "Gemini.md"],
    },
    {
      text: "条款与政策",
      icon: "scale-balanced",
      prefix: "tos/",
      collapsible: true,
      children: [
        "aup.md",
        "TOS.md",
        "service-specific-terms.md",
        "use.md",
      ],
    },
  ],
});
